{% set name = "emoji-extractor" %}
{% set version = "17.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/emoji_extractor-{{ version }}.tar.gz
  sha256: 22a16b056648a3d69554ff1f639b0e9760be95b95b772d77e68646236d0e3ed6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - emoji_extractor
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/alexanderrobertson/emoji-extractor
  dev_url: https://github.com/alexanderrobertson/emoji-extractor
  summary: Extract, detect and count emoji
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - alexanderrobertson
